export const INSERT_REQUESTED = 'orders/INSERT_REQUESTED'
export const INSERT = 'orders/INSERT'
export const LIST_REQUESTED = 'orders/LIST_REQUESTED'
export const LIST = 'orders/LIST'
export const UPDATE_REQUESTED = 'orders/UPDATE_REQUESTED'
export const UPDATE = 'orders/UPDATE'
export const DELETE_REQUESTED = 'orders/DELETE_REQUESTED'
export const DELETE = 'orders/DELETE'